# Generated by Django 4.1.7 on 2023-02-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resturant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant english title"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Resturant english description"),
                ),
                (
                    "opening_sentence_en",
                    models.CharField(
                        max_length=255, verbose_name="opening sentence english title"
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant english address"
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(max_length=15, verbose_name="phone number"),
                ),
                (
                    "logo",
                    models.ImageField(
                        null=True,
                        upload_to="resturant/logo/",
                        verbose_name="logo Image",
                    ),
                ),
                ("demo_url", models.URLField(null=True, verbose_name="demo url")),
                (
                    "email_address",
                    models.EmailField(
                        max_length=254, verbose_name="Resturant Email Address"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(null=True, verbose_name="facebook url"),
                ),
                ("twitter_url", models.URLField(null=True, verbose_name="twitter url")),
                (
                    "instgram_url",
                    models.URLField(null=True, verbose_name="instgram url"),
                ),
                ("youtube_url", models.URLField(null=True, verbose_name="youtube url")),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant arabic title"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="Resturant arabic description"),
                ),
                (
                    "opening_sentence_ar",
                    models.CharField(
                        max_length=255, verbose_name="opening sentence arabic title"
                    ),
                ),
                (
                    "address_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant arabic address"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant",
            },
        ),
        migrations.CreateModel(
            name="ResturantAboutPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        verbose_name="Resturant About Place english title",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        verbose_name="Resturant About Place english description"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255,
                        verbose_name="Resturant About Place arabic title",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        verbose_name="Resturant About Place arabic description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant/place/",
                        verbose_name="About Place image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant About Place",
            },
        ),
        migrations.CreateModel(
            name="ResturantCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0, verbose_name="total")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Menu Cart",
            },
        ),
        migrations.CreateModel(
            name="ResturantChifs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chif_name_en",
                    models.CharField(max_length=200, verbose_name="chif english name"),
                ),
                (
                    "chif_proffesion_en",
                    models.CharField(
                        max_length=200, verbose_name="chif english proffesion"
                    ),
                ),
                (
                    "chif_profile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant/chef_profile/",
                        verbose_name="chif profile",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(null=True, verbose_name="facebook url"),
                ),
                ("twitter_url", models.URLField(null=True, verbose_name="twitter url")),
                (
                    "instgram_url",
                    models.URLField(null=True, verbose_name="instgram url"),
                ),
                (
                    "linkedin_url",
                    models.URLField(null=True, verbose_name="linkedIn url"),
                ),
                (
                    "chif_name_ar",
                    models.CharField(max_length=200, verbose_name="chif arabic name"),
                ),
                (
                    "chif_proffesion_ar",
                    models.CharField(
                        max_length=200, verbose_name="chif arabic proffesion"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Chifs",
            },
        ),
        migrations.CreateModel(
            name="ResturantEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event english title"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        verbose_name="Resturant event english description"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event arabic title"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="Resturant event arabic description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant/events/",
                        verbose_name="event image",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Resturant event price",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Events",
            },
        ),
        migrations.CreateModel(
            name="ResturantGalaryImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="resturant/galary_images/",
                        verbose_name="Resturant Galary Images",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Galary Images",
            },
        ),
        migrations.CreateModel(
            name="ResturantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="menu item english title"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="menu item english description"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, verbose_name="menu item arabic title"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="menu item arabic description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="menu item price"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Menu",
            },
        ),
        migrations.CreateModel(
            name="ResturantMenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="menu category english title"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, verbose_name="menu category arabic title"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Menu Category",
            },
        ),
        migrations.CreateModel(
            name="ResturantSiteImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="resturant/site_images/",
                        verbose_name="Resturant Site Images",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Site Images",
            },
        ),
        migrations.CreateModel(
            name="ResturantSpecials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_title_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event english title"
                    ),
                ),
                (
                    "full_title_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event english title"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        verbose_name="Resturant event english description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant/specials/",
                        verbose_name="image",
                    ),
                ),
                (
                    "short_title_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event arabic title"
                    ),
                ),
                (
                    "full_title_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant event arabic title"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="Resturant event arabic description"),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Specials",
            },
        ),
        migrations.CreateModel(
            name="ResturantTableReservasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email Adress"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Time")),
                (
                    "number_of_people",
                    models.PositiveIntegerField(verbose_name="Number of people"),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name_plural": "Resturant Table Reservasion",
            },
        ),
        migrations.CreateModel(
            name="ResturantTestimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="english name"),
                ),
                (
                    "proffesion_en",
                    models.CharField(max_length=200, verbose_name="english proffesion"),
                ),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant/testimonials/",
                        verbose_name="profile",
                    ),
                ),
                ("quote_en", models.TextField(verbose_name="english quote")),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="arabic name"),
                ),
                (
                    "proffesion_ar",
                    models.CharField(max_length=200, verbose_name="arabic proffesion"),
                ),
                ("quote_ar", models.TextField(verbose_name="arabic quote")),
            ],
            options={
                "verbose_name_plural": "ResturantTestimonials",
            },
        ),
        migrations.CreateModel(
            name="ResturantWhyUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, verbose_name="Resturant WhyUs english title"
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        max_length=255,
                        verbose_name="Resturant WhyUs english description",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, verbose_name="Resturant WhyUs arabic title"
                    ),
                ),
                (
                    "description_ar",
                    models.CharField(
                        max_length=255,
                        verbose_name="Resturant WhyUs arabic description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant WhyUs",
            },
        ),
        migrations.CreateModel(
            name="ResturantMenuOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(max_length=15, verbose_name="phone number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                ("subtotal", models.PositiveIntegerField(verbose_name="subtotal")),
                ("total", models.PositiveIntegerField(verbose_name="total")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        max_length=200, null=True, verbose_name="payment mode"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        max_length=200, null=True, verbose_name="payment id"
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant.resturantcart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Menu Order",
            },
        ),
        migrations.CreateModel(
            name="ResturantMenuCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.PositiveIntegerField(verbose_name="rate")),
                ("subtotal", models.PositiveIntegerField(verbose_name="subtotal")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant.resturantcart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant.resturantmenu",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Menu Cart",
            },
        ),
        migrations.AddField(
            model_name="resturantmenu",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant.resturantmenucategory",
                verbose_name="menu category",
            ),
        ),
        migrations.CreateModel(
            name="ResturantClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="full_name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="address"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resturant_client/",
                        verbose_name="image",
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                (
                    "join_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="join_on"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resturant Client",
            },
        ),
    ]
