# Generated by Django 4.1.7 on 2023-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantmenu",
            name="description_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="menu item arabic description"
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenu",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="menu item english description"
            ),
        ),
    ]
