# Generated by Django 4.1.7 on 2023-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0003_alter_resturanttablereservasion_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturantmenucart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
