# Generated by Django 4.1.7 on 2023-02-21 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resturant", "0004_resturantmenucart_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resturantclient",
            name="client",
        ),
        migrations.AddField(
            model_name="resturantclient",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
            preserve_default=False,
        ),
    ]
