# Generated by Django 4.1.7 on 2023-02-23 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resturant", "0005_remove_resturantclient_client_resturantclient_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resturantcart",
            options={"verbose_name_plural": "Resturant Cart"},
        ),
        migrations.AlterField(
            model_name="resturantcart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenu",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=5, verbose_name="menu item price"
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenucart",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
    ]
