# Generated by Django 4.1.7 on 2023-02-24 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "resturant",
            "0006_alter_resturantcart_options_alter_resturantcart_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resturantmenuorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Order Received", "Order Received"),
                    ("Order Processing", "Order Processing"),
                    ("Order On The Way", "Order On The Way"),
                    ("Order Completed", "Order Completed"),
                    ("Order Canceled", "Order Canceled"),
                ],
                default="Order Received",
                max_length=50,
                verbose_name="order status",
            ),
        ),
        migrations.CreateModel(
            name="ResturantAdmins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
