# Generated by Django 4.1.7 on 2023-02-24 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resturant", "0007_resturantmenuorder_order_status_resturantadmins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantadmins",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="resturantadmins",
            name="mobile",
            field=models.CharField(max_length=20, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="resturantadmins",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
    ]
