# Generated by Django 4.1.7 on 2023-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0008_alter_resturantadmins_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturanttablereservasion",
            name="confirm",
            field=models.BooleanField(default=False, verbose_name="Confirm"),
        ),
    ]
