# Generated by Django 4.1.7 on 2023-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resturant",
            "0010_alter_resturantcart_total_alter_resturantmenu_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantcart",
            name="total",
            field=models.FloatField(default=0.0, verbose_name="total"),
        ),
        migrations.AlterField(
            model_name="resturantmenuorder",
            name="total",
            field=models.FloatField(default=0.0, verbose_name="total"),
        ),
    ]
