# Generated by Django 4.1.7 on 2023-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0011_alter_resturantcart_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantcart",
            name="total",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=6, verbose_name="total"
            ),
        ),
    ]
