# Generated by Django 4.1.7 on 2023-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0012_alter_resturantcart_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantmenuorder",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenuorder",
            name="total",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=6, verbose_name="total"
            ),
        ),
    ]
