# Generated by Django 4.1.7 on 2023-03-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0013_alter_resturantmenuorder_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resturantadmins",
            options={"verbose_name_plural": "Resturant Admins"},
        ),
    ]
