# Generated by Django 4.1.7 on 2023-03-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0014_alter_resturantadmins_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturantmenu",
            name="image",
            field=models.ImageField(
                null=True, upload_to="menu-item/images/", verbose_name="menu item image"
            ),
        ),
    ]
