# Generated by Django 4.1.7 on 2023-03-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0015_resturantmenu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturantmenu",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="menu-item/images/",
                verbose_name="menu item image",
            ),
        ),
    ]
