# Generated by Django 4.1.7 on 2023-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant", "0016_alter_resturantmenu_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturantmenu",
            name="mediam_price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="menu item mediam price",
            ),
        ),
        migrations.AddField(
            model_name="resturantmenu",
            name="small_price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="menu item small price",
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenu",
            name="description_ar",
            field=models.TextField(
                null=True, verbose_name="menu item arabic description"
            ),
        ),
        migrations.AlterField(
            model_name="resturantmenu",
            name="description_en",
            field=models.TextField(
                null=True, verbose_name="menu item english description"
            ),
        ),
    ]
